// Code generated by MockGen. DO NOT EDIT.
// Source: fwd.go

// Package main is a generated GoMock package.
package main

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// Mockibool is a mock of ibool interface
type Mockibool struct {
	ctrl     *gomock.Controller
	recorder *MockiboolMockRecorder
}

// MockiboolMockRecorder is the mock recorder for Mockibool
type MockiboolMockRecorder struct {
	mock *Mockibool
}

// NewMockibool creates a new mock instance
func NewMockibool(ctrl *gomock.Controller) *Mockibool {
	mock := &Mockibool{ctrl: ctrl}
	mock.recorder = &MockiboolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Mockibool) EXPECT() *MockiboolMockRecorder {
	return m.recorder
}

// value mocks base method
func (m *Mockibool) value() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "value")
	ret0, _ := ret[0].(bool)
	return ret0
}

// value indicates an expected call of value
func (mr *MockiboolMockRecorder) value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "value", reflect.TypeOf((*Mockibool)(nil).value))
}
